title: Manuel Martinez Urbina
logo: /assets/img/LinkedinPic.jpeg
description: Economics B.S.
International Studies B.S. 
Mathematics Minor
Graduated from the University of Michigan
# show_downloads: true
theme: jekyll-theme-minimal
