title: Manuel Martinez Urbina
logo: /assets/img/LinkedinPic.jpeg
description: Economics B.S.
description: International Studies B.S.
description: Mathematics Minor
description: Graduated from the University of Michigan-Ann Arbor
# show_downloads: true
theme: jekyll-theme-minimal
