title: Manuel Martinez Urbina
logo: /assets/img/LinkedinPic.jpeg
description: Economics B.S., International Studies B.S., and Mathematics Minor from the University of Michigan
# show_downloads: true
theme: jekyll-theme-minimal
